# Generated by Django 5.1.1 on 2024-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='es_modificable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='turno',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('rut_trabajador', 'fecha_inicio', 'fecha_fin')},
        ),
    ]
