# Generated by Django 5.1.1 on 2024-11-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_turno_es_modificable_turno_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('NO_ASIGNADO', 'No Asignado'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='NO_ASIGNADO', max_length=20),
        ),
    ]
