# Generated by Django 5.1.1 on 2024-11-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_alter_turno_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurnoAprobado',
        ),
    ]
