# Generated by Django 5.1.1 on 2024-11-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_turno_fecha_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
