# Generated by Django 5.1.1 on 2024-10-24 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('usuarios', 'Reporte de Usuarios'), ('turnos_talana', 'Reporte de Turnos TALANA'), ('turnos_general', 'Reporte de Turnos General')], max_length=50)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('url_descarga', models.CharField(max_length=255)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
