# Generated by Django 5.1.1 on 2024-10-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
