# Generated by Django 5.1.1 on 2024-11-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0002_delete_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('turnos', 'Reporte de Turnos'), ('usuarios', 'Reporte de Usuarios'), ('talana', 'Reporte TALANA')], max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('trabajador', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_reporte', models.FileField(upload_to='reportes/')),
            ],
        ),
    ]
