# Generated by Django 5.1.1 on 2024-11-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportegenerado',
            name='trabajador',
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='archivo_reporte',
            field=models.FileField(upload_to='reporte/'),
        ),
    ]
