# Generated by Django 5.1.1 on 2024-10-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0005_alter_perfil_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='rut',
        ),
    ]
