# Generated by Django 5.1.1 on 2024-10-21 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0010_perfil_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
    ]
