# Generated by Django 5.1.1 on 2024-11-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0015_perfil_fecha_aprobacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_aprobacion',
        ),
    ]
